import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
from datetime import datetime

load_dotenv('config/.env')

class EmailAlerts:
    """Send email alerts for air quality"""
    
    def __init__(self):
        self.smtp_server = os.getenv('SMTP_SERVER')
        self.smtp_port = int(os.getenv('SMTP_PORT'))
        self.email_address = os.getenv('EMAIL_ADDRESS')
        self.email_password = os.getenv('EMAIL_PASSWORD')
        self.alert_email = os.getenv('ALERT_EMAIL')
    
    def send_email(self, subject, body):
        """Send email notification"""
        try:
            # Create message
            message = MIMEMultipart("alternative")
            message["Subject"] = subject
            message["From"] = self.email_address
            message["To"] = self.alert_email
            
            # Create HTML content
            html = f"""
            <html>
                <body style="font-family: Arial, sans-serif;">
                    <div style="background-color: #f8f9fa; padding: 20px; border-radius: 10px;">
                        <h2 style="color: #e74c3c;">🚨 Air Quality Alert</h2>
                        {body}
                        <hr>
                        <p style="color: #7f8c8d; font-size: 12px;">
                            Generated by Air Pollution Monitoring System<br>
                            Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
                        </p>
                    </div>
                </body>
            </html>
            """
            
            # Attach HTML content
            html_part = MIMEText(html, "html")
            message.attach(html_part)
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.email_address, self.email_password)
                server.send_message(message)
            
            print(f"✅ Email sent successfully to {self.alert_email}")
            return True
            
        except Exception as e:
            print(f"❌ Error sending email: {e}")
            return False
    
    def send_alert(self, city, aqi, category, health_message):
        """Send pollution alert email"""
        subject = f"⚠️ Air Quality Alert - {city} (AQI: {aqi})"
        
        body = f"""
        <h3 style="color: #e74c3c;">📍 Location: {city}</h3>
        <p style="font-size: 18px;"><strong>Current AQI: {aqi}</strong> ({category})</p>
        
        <div style="background-color: #fff3cd; padding: 15px; border-left: 4px solid #ffc107; margin: 20px 0;">
            <h4 style="margin-top: 0;">💬 Health Advisory:</h4>
            <p>{health_message}</p>
        </div>
        
        <h4>📋 Recommendations:</h4>
        <ul>
            <li>Keep windows and doors closed</li>
            <li>Use air purifiers indoors</li>
            <li>Wear N95 masks if going outside</li>
            <li>Avoid outdoor exercise</li>
        </ul>
        
        <p style="color: #7f8c8d; font-style: italic;">
            Stay safe and monitor air quality regularly.
        </p>
        """
        
        return self.send_email(subject, body)
    
    def send_daily_report(self, report_data):
        """Send daily summary report"""
        subject = f"📊 Daily Air Quality Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Create city table
        cities_html = ""
        for city in report_data:
            color = "#27ae60" if city['aqi'] < 100 else "#f39c12" if city['aqi'] < 200 else "#e74c3c"
            cities_html += f"""
            <tr>
                <td style="padding: 10px; border-bottom: 1px solid #ddd;">{city['name']}</td>
                <td style="padding: 10px; border-bottom: 1px solid #ddd; color: {color}; font-weight: bold;">{city['aqi']}</td>
                <td style="padding: 10px; border-bottom: 1px solid #ddd;">{city['category']}</td>
            </tr>
            """
        
        body = f"""
        <h3>🌍 Air Quality Summary</h3>
        <p>Here's your daily air quality report for major Indian cities:</p>
        
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
            <thead>
                <tr style="background-color: #3498db; color: white;">
                    <th style="padding: 10px; text-align: left;">City</th>
                    <th style="padding: 10px; text-align: left;">AQI</th>
                    <th style="padding: 10px; text-align: left;">Category</th>
                </tr>
            </thead>
            <tbody>
                {cities_html}
            </tbody>
        </table>
        
        <div style="background-color: #e8f5e9; padding: 15px; border-radius: 5px; margin-top: 20px;">
            <p style="margin: 0;">
                <strong>✅ Tip:</strong> Check the full report for detailed analysis and predictions.
            </p>
        </div>
        """
        
        return self.send_email(subject, body)

if __name__ == "__main__":
    # Test email
    print("Testing email alert system...")
    print()
    
    email_system = EmailAlerts()
    
    # Send test alert
    success = email_system.send_alert(
        city="Delhi",
        aqi=287,
        category="Poor",
        health_message="Everyone should avoid prolonged outdoor exertion. Wear N95 masks if going outside."
    )
    
    if success:
        print("\n✅ Test email sent! Check your inbox: saswatkhandai@gmail.com")
    else:
        print("\n❌ Failed to send test email")